artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_file: 'C:/Users/Hardik0436/Downloads/MURA-v1.1.zip'
  local_data: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

preprocess_data:
  root_dir: artifacts/preprocess
  train_file_path: artifacts/preprocess/train.csv
  test_file_path: artifacts/preprocess/test.csv

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/model.keras
  updated_base_model_path: artifacts/prepare_base_model/update_base_model.keras

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5