artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_file: 'C:/Users/hardi/Downloads/MURA-v1.1.zip'
  local_data: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

preprocess_data:
  root_dir: artifacts/preprocess
  train_file_path: artifacts/preprocess/train.csv
  test_file_path: artifacts/preprocess/test.csv

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/update_base_model.h5

